spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todoeod
    username: todo
    password: todo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{correlationId}] %logger{36} - %msg%n"

eod:
  webhooks:
    github:
      secret: ""
    gitlab:
      secret: ""
  rateLimit:
    perOriginPerMinute: 600
  idempotency:
    ttlSeconds: 86400
  security:
    enabled: false
    jwt:
      secret: ${APP_JWT_SECRET:change-me}
