name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & test (backend)
        run: mvn -B -ntp -DskipTests=false -f backend/pom.xml verify

      - name: Ensure jq is available
        if: always()
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y jq
          fi

      - name: Check versioned OpenAPI JSON exists
        run: |
          set -euo pipefail
          VER=$(mvn -q -f backend/pom.xml help:evaluate -Dexpression=project.version -DforceStdout)
          BASEVER=${VER%-SNAPSHOT}
          echo "Project version: $VER (base: $BASEVER)"
          CANDIDATES=("docs/openapi/openapi-${VER}.json")
          if [[ "$VER" != "$BASEVER" ]]; then
            CANDIDATES+=("docs/openapi/openapi-${BASEVER}.json")
          fi
          FOUND=""
          for f in "${CANDIDATES[@]}"; do
            if [[ -f "$f" ]]; then
              echo "Found OpenAPI file: $f"
              FOUND="$f"
              break
            fi
          done
          if [[ -z "$FOUND" ]]; then
            echo "::error title=Missing OpenAPI file::Expected one of: ${CANDIDATES[*]}"
            echo "Hint: run the app locally and generate from /v3/api-docs."
            exit 1
          fi
          if ! jq -e . "$FOUND" >/dev/null 2>&1; then
            echo "::error title=Invalid JSON::$FOUND is not valid JSON."
            exit 1
          fi
