name: Post-release version bump

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Compute next snapshot version
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ github.event.release.tag_name }}"  # e.g., v0.2.0
          VER="${TAG#v}"
          IFS='.' read -r MA MI PA <<< "$VER"
          # bump minor -> next .0-SNAPSHOT
          NEXT_VER="${MA}.$((MI+1)).0-SNAPSHOT"
          echo "release_tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "release_ver=$VER" >> "$GITHUB_OUTPUT"
          echo "next_snapshot=$NEXT_VER" >> "$GITHUB_OUTPUT"
          echo "Release: $VER -> Next: $NEXT_VER"

      - name: Bump backend/pom.xml to next SNAPSHOT
        shell: bash
        run: |
          set -euo pipefail
          NEXT="${{ steps.ver.outputs.next_snapshot }}"
          awk -v next="$NEXT" '
            BEGIN{seen=0;done=0}
            {
              if(!done){
                if($0 ~ /<artifactId>eod-backend<\/artifactId>/){ seen=1 }
                else if(seen && $0 ~ /<version>[^<]+<\/version>/){
                  sub(/<version>[^<]+<\/version>/, "<version>" next "</version>")
                  done=1; seen=0
                }
              }
              print
            }
          ' backend/pom.xml > backend/pom.xml.tmp && mv backend/pom.xml.tmp backend/pom.xml
          echo "New POM version:" $(grep -m1 -oE '<version>[^<]+' backend/pom.xml | cut -d'>' -f2)

      - name: Update CHANGELOG Unreleased link
        shell: bash
        run: |
          set -euo pipefail
          REPO="${{ github.repository }}"
          REL="${{ steps.ver.outputs.release_ver }}"
          if grep -q "^\[Unreleased\]:" CHANGELOG.md; then
            sed -i -E "s#^\[Unreleased\]:.*#[Unreleased]: https://github.com/${REPO}/compare/v${REL}...HEAD#" CHANGELOG.md
          else
            echo "[Unreleased]: https://github.com/${REPO}/compare/v${REL}...HEAD" >> CHANGELOG.md
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore(version): bump to ${{ steps.ver.outputs.next_snapshot }}

            - Update backend/pom.xml
            - Update CHANGELOG Unreleased link to compare v${{ steps.ver.outputs.release_ver }}...HEAD
          title: "chore(version): bump to ${{ steps.ver.outputs.next_snapshot }}"
          body: |
            Post-release automation.

            - Release tag: v${{ steps.ver.outputs.release_ver }}
            - Next development version: ${{ steps.ver.outputs.next_snapshot }}
            - CHANGELOG Unreleased now compares v${{ steps.ver.outputs.release_ver }}...HEAD

            Follow-up:
            - Generate `docs/openapi/openapi-${{ steps.ver.outputs.next_snapshot }}.json` when API changes, or rely on last release spec until then (CI allows fallback).
          branch: chore/bump-${{ steps.ver.outputs.next_snapshot }}
          delete-branch: true
          base: main
